from config.enums import PhaseState as ws

PHASE_TRANSITIONS = {
    ws.NEW: [ws.COLLECTING, ws.FAILED],
    ws.COLLECTING: [ws.READY, ws.COLLECTING, ws.FAILED, ws.PAUSED],
    ws.READY: [ws.PROCESSING, ws.PRESENTING, ws.FAILED, ws.PAUSED],
    ws.PROCESSING: [ws.PRESENTING, ws.AWAITING_DECISION, ws.FAILED, ws.PAUSED],
    ws.PRESENTING: [ws.AWAITING_DECISION, ws.COLLECTING, ws.FAILED, ws.PAUSED],
    ws.AWAITING_DECISION: [ws.PROCESSING, ws.COLLECTING, ws.FAILED, ws.PAUSED],
    ws.COMPLETED: [],
    ws.FAILED: [ws.COLLECTING, ws.COMPLETED],
    ws.PAUSED: [ws.COLLECTING, ws.READY, ws.AWAITING_DECISION],
}