from config.enums import PhaseState as ps, WorkstreamState as ws

WS_TRANSITIONS = {
    ws.NEW: [ws.ACTIVE],
    ws.ACTIVE: [ws.ACTIVE, ws.PENDING, ws.ABORTED, ws.COMPLETED],
    ws.PENDING: [ws.ACTIVE],
}

PHASE_TRANSITIONS = {
    ps.NEW: [ps.COLLECTING, ps.FAILED],
    ps.COLLECTING: [ps.READY, ps.COLLECTING, ps.FAILED, ps.PAUSED],
    ps.READY: [ps.PROCESSING, ps.PRESENTING, ps.FAILED, ps.PAUSED],
    ps.PROCESSING: [ps.PRESENTING, ps.AWAITING_DECISION, ps.FAILED, ps.PAUSED],
    ps.PRESENTING: [ps.AWAITING_DECISION, ps.COLLECTING, ps.FAILED, ps.PAUSED],
    ps.AWAITING_DECISION: [ps.PROCESSING, ps.COLLECTING, ps.FAILED, ps.PAUSED],
    ps.COMPLETED: [],
    ps.FAILED: [ps.COLLECTING, ps.COMPLETED],
    ps.PAUSED: [ps.COLLECTING, ps.READY, ps.AWAITING_DECISION],
}