# core/fsm_rules.py
DISCOVERY_TRANSITIONS = {
    "NEW": ["COLLECTING"],
    "COLLECTING": ["READY", "COLLECTING"],  # loop until slots ready
    "READY": ["PROCESSING"],
    "PROCESSING": ["PRESENTING", "FAILED"],
    "PRESENTING": ["AWAITING_DECISION"],
    "AWAITING_DECISION": ["PROCESSING", "CONFIRMING"],
    "CONFIRMING": ["COMPLETED"],
    "FAILED": ["COLLECTING", "COMPLETED"]
}

ORDER_TRANSITIONS = {
    "NEW": ["COLLECTING"],
    "COLLECTING": ["CONFIRMING"],
    "CONFIRMING": ["COMPLETED", "FAILED"],
    "COMPLETED": [],
    "FAILED": []
}
