# core/states.py
from enum import Enum

class DiscoveryState(Enum):
    NEW = "NEW"
    COLLECTING = "COLLECTING"
    READY = "READY"
    PROCESSING = "PROCESSING"
    PRESENTING = "PRESENTING"
    AWAITING_DECISION = "AWAITING_DECISION"
    CONFIRMING = "CONFIRMING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class OrderState(Enum):
    NEW = "NEW"
    COLLECTING = "COLLECTING"
    CONFIRMING = "CONFIRMING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"

class WorkstreamState(Enum):
    NEW =  "NEW"
    COLLECTING = "COLLECTING"
    READY = "READY"
    PROCESSING = "PROCESSING"
    PRESENTING = "PRESENTING"
    AWAITING_DECISION = "AWAITING_DECISION"
    CONFIRMING = "CONFIRMING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    PAUSED = "PAUSED"
